const Student=[
    {
        "id":0,
        "Name":"PRIYA",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":1,
        "Name":"DHARSHINI",
        "Age":"25",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":2,
        "Name":"RAJA",
        "Age":"22",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":3,
        "Name":"SEKER",
        "Age":"21",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":4,
        "Name":"SANGEETHA",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":5,
        "Name":"JOSAN",
        "Age":"29",
        "Course":"MERN",
        "Batch":"October"
    },
    {
        "id":6,
        "Name":"SANJAY",
        "Age":"23",
        "Course":"MERN",
        "Batch":"October"
    },
]
export default Student